# Generated by Django 4.1.7 on 2023-06-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_room', '0002_alter_requestroom_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestroom',
            name='type',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=2, max_length=1),
        ),
    ]
