# Generated by Django 4.1.7 on 2023-06-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_room', '0003_requestroom_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestroom',
            name='type',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=2),
        ),
    ]
